defaults:
  - agent: sac

model:
  _target_: mbrl.models.Ensemble
  ensemble_size: 7
  in_size: ???
  out_size: ???
  member_cfg: ${member_cfg}
  device: ${device}
  optim_lr: 0.0075 # TODO this should be moved out of the ensemble class

member_cfg:
  _target_: mbrl.models.GaussianMLP
  device: ${model.device}
  num_layers: 4
  in_size: ${model.in_size}
  out_size: ${model.out_size}
  hid_size: 200

env: "hopper--stand"

env_dataset_size: 1000
validation_ratio: 0.1
dynamics_model_batch_size: 256
initial_exploration_steps: 20
num_epochs: 100
freq_train_dyn_model: 1
patience: 5
rollouts_per_step: 2
rollout_horizon: 2 # TODO replace by thresholded linear
rollout_batch_size: 32
sac_buffer_capacity: ???
sac_samples_action: true
num_sac_updates_per_rollout: 100

seed: 0

device: "cuda:0"

log_frequency_sac: 1
log_save_tb: false
log_frequency_model: 5

eval_freq: 1
num_eval_episodes: 1
save_video: true

experiment: test_exp

hydra:
    run:
        dir: ./exp/mbrl/${env}/${now:%Y.%m.%d}/${now:%H%M}_${experiment}