# @package _group_
model:
  _target_: mbrl.models.GaussianMLP
  device: ${device}
  num_layers: 4
  in_size: ???
  out_size: ???
  ensemble_size: 1
  hid_size: 200
  use_silu: False 
  deterministic: false
  activation_fn_cfg: ${dynamics_model.activation_fn_cfg}

activation_fn_cfg:
  _target_: torch.nn.Threshold
  threshold: 0.5
  value: 10
